name: gg_json_hash
description: Hashes JSON objects deeply. Good or JSON comparison, sync and more.
version: 4.0.1
repository: https://github.com/inlavigo/gg_json_hash.git

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  crypto: ^3.0.6

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
